apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-score-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-score
  template:
    metadata:
      labels:
        app: nodejs-score
    spec:
      containers:
        - name: nodejs-score
          image: dragosc/node-password-score
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
---
apiVersion: v1
kind: Service
metadata:
  name: score-service
spec:
  selector:
    app: nodejs-score
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
