apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-common-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-common
  template:
    metadata:
      labels:
        app: nodejs-common
    spec:
      containers:
        - name: nodejs-common
          image: dragosc/node-password-common
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
---
apiVersion: v1
kind: Service
metadata:
  name: common-service
spec:
  selector:
    app: nodejs-common
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
