apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-reuse-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-reuse
  template:
    metadata:
      labels:
        app: nodejs-reuse
    spec:
      containers:
        - name: nodejs-reuse
          image: dragosc/node-password-reuse
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
---
apiVersion: v1
kind: Service
metadata:
  name: reuse-service
spec:
  selector:
    app: nodejs-reuse
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
